GET http://localhost:8080/products?page=1&limit=2&sort=asc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA0MzMzMDYsInN1YiI6ImQ5NTAxY2FiLTlhMjQtNGM4NC1hNmM3LTgxOTcxM2E1ODI2NiJ9.pfHGZxEjgy3YWAm39Hub83rMkygCDJEm-q9rvGlzXjY

###

# @name createProduct
POST http://localhost:8080/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

###


GET http://localhost:8080/products/32fd3c83-0491-409e-ac14-cb8bc93beb06

###


PUT http://localhost:8080/products/32fd3c83-0491-409e-ac14-cb8bc93beb06
Content-Type: application/json

{
    "name": "Product 1 Updated",
    "price": 200
}

###

DELETE http://localhost:8080/products/97168926-4ed3-4858-a1cc-f63d89e65df3

###


###

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "123456"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "123456"
}